name: Update Witchcraft DNS

on:
  push:
    branches: [ master ]

jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version
      id: get_version
      run: |
        # 从 metadata.json 提取版本号（确保文件名和路径正确）
        VERSION=$(jq -r '.version' mod.json)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Update TXT Record
      run: |
        # 调用 Cloudflare API 更新指定子域名
        curl -X PUT "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/dns_records/${{ secrets.CLOUDFLARE_RECORD_ID }}" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{
            "type": "TXT",
            "name": "witchcraft.325477.xyz",
            "content": "${{ steps.get_version.outputs.version }}",
            "ttl": 3600,
            "proxied": false,
            "comment": "Auto-updated by GitHub Actions"
          }'
