name: Update DNS Version

on:
  push:
    branches: [ master ]

jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version
      id: get_version
      run: |
        VERSION=$(jq -r '.version' metadata.json)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Update Cloudflare DNS
      run: |
        curl -X PUT "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/dns_records/${{ secrets.CLOUDFLARE_RECORD_ID }}" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{
            "type": "TXT",
            "name": "y325477.xyz",  # 替换为你的域名
            "content": "'"${{ steps.get_version.outputs.version }}"'",
            "ttl": 120
          }'
